### ISSUE TITLE
The Z parameter in get_elev_raster function

### ISSUE THREAD

**Issue by 12038019** [jhollist/elevatr#75]
Dear, Jhollist
There is a confusing question I want to ask you.
I have no idea how to get the SRTM 90m DEM data by setting the Z value.
I change the Z value to 11 and 12 respectively,  but the resolutions are 0.000154  and 0.000309.
To my knowledge,  the resolution of SRTM90m is about 0.00083.
I look forward to your reply, much appreciated!!

**Comment by raruggie** [comment]
I am also confused on how to use the z parameter. Is ground resolution (https://github.com/tilezen/joerd/blob/master/docs/data-sources.md#what-is-the-ground-resolution) the same as the spatial resolution?

Also, can you explain the behavior of the z-parameter here? Changing z from 7 to 9 results in different values:
https://rspatialdata.github.io/elevation.html

**Comment by jhollist** [comment]
@12038019 If you are using the "aws" as the `src` then you will not be able to get only SRTM.  The "aws" uses the Terrain Tiles which are a combination of data sources and they return a dataset at a specified zoom level (i.e. z).  If you want just SRTM, use either the "sl3" src which will return the 90 meter SRTM or "sl1" which returns the 30 meter SRTM.  Since the resolution of these are fixed, be careful with the extent of your request.  

@raruggie It may be clear from above, but to be sure, the z argument is used to specify what level of zoom to use for grabbing the AWS terrain tiles.  As zoom gets larger, the resolution (ground and spatial are the same thing) will get smaller.  A zoom of 14 returns smaller pixels than a zoom of 10, for instance.  The size of those pixels can vary, even with the same zoom, as the final projection and the latitude of the requested area will impact that.

Hope this helps, and @12038019 sorry for delay in responding!

**Comment by 12038019** [comment]
@jhollist Thanks for your kind reply !

**Comment by 12038019** [comment]
@jhollist But we just can choose the src form one of the “aws”, “gl3”, “gl1”, “alos”, “srtm15plus”, I can not find the "sl3" or ""sl1""src.

**Comment by jhollist** [comment]
Apologies!  Typo on my part.  gl3 and gl1 are the srtm options.

**Comment by jhollist** [comment]
Closing this as it seems resolved.  Feel free to reopen if you are still having issues.
